# Generated by Django 3.2.13 on 2022-06-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_place_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='image',
            new_name='img',
        ),
    ]
