# Generated by Django 3.2.13 on 2022-06-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_rename_image_place_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=300)),
                ('img1', models.ImageField(upload_to='pic')),
                ('desc', models.TextField()),
            ],
        ),
    ]
